In [60]:
import os
import struct
import numpy as np
import matplotlib.pyplot as plt
import skimage
from PIL import Image
import rasterio

In [64]:
lines = 3336
samples = 6066

filename = 'arist_rat_level2.img'
intype = ">f4"
outtype = np.float32
f = open(filename, 'rb')
data_raw = np.fromfile(f, intype)
data = data_raw.reshape(lines, samples).astype(outtype)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [65]:
print(np.nanmean(data))

0.1813118


In [63]:
outfile = "arist_rat_level2.tif"
outds = rasterio.open(outfile, 'w', driver='GTiff', 
                  height = lines, 
                  width = samples, 
                  count=1, 
                  crs = None, 
                  dtype = outtype,
                  transform = None,
                  compress='lzw',
                  nodata = np.nan)
outds.write(data, 1)